import React, { useState } from 'react';
import { Card } from './ui/Card';
import ParetoFront from './visualization/ParetoFront';
import SolutionsTable from './visualization/SolutionsTable';
import CityGraph from './visualization/CityGraph';

const Visualization: React.FC = () => {
  const [activeInstance, setActiveInstance] = useState('kroAB100');
  const [selectedSolution, setSelectedSolution] = useState<number | null>(null);
  
  const instances = [
    { id: 'kroAB100', name: 'kroAB100 (100 cities)' },
    { id: 'kroAB150', name: 'kroAB150 (150 cities)' },
    { id: 'kroAB200', name: 'kroAB200 (200 cities)' },
    { id: 'custom', name: 'Custom Instance (40 cities)' },
  ];

  return (
    <div className="p-6 max-w-6xl mx-auto">
      <h2 className="text-2xl font-bold mb-4">Solution Visualization</h2>
      <p className="mb-6">
        Visualize the Pareto-optimal solutions generated by the DRL-MOA model for different problem instances.
      </p>

      <div className="mb-6">
        <div className="flex space-x-2 overflow-x-auto pb-2">
          {instances.map(instance => (
            <button
              key={instance.id}
              className={`px-4 py-2 rounded-lg ${activeInstance === instance.id 
                ? 'bg-blue-500 text-white' 
                : 'bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-800 dark:text-gray-200'}`}
              onClick={() => setActiveInstance(instance.id)}
            >
              {instance.name}
            </button>
          ))}
        </div>
      </div>

      <div className="grid md:grid-cols-3 gap-6">
        <div className="md:col-span-2">
          <Card className="p-6">
            <h3 className="text-lg font-semibold mb-4">Pareto Front</h3>
            <div className="h-96">
              <ParetoFront instanceId={activeInstance} onSelectSolution={setSelectedSolution} selectedSolution={selectedSolution} />
            </div>
          </Card>
        </div>
        
        <div className="md:col-span-1">
          <Card className="p-6">
            <h3 className="text-lg font-semibold mb-4">Solutions</h3>
            <SolutionsTable 
              instanceId={activeInstance} 
              onSelectSolution={setSelectedSolution}
              selectedSolution={selectedSolution}
            />
          </Card>
        </div>
      </div>
      
      <div className="mt-6">
        <Card className="p-6">
          <h3 className="text-lg font-semibold mb-4">Solution Visualization</h3>
          {selectedSolution !== null ? (
            <div className="grid md:grid-cols-2 gap-6 h-[400px]">
              <div className="h-full">
                <h4 className="text-sm font-medium mb-2">Objective 1 Solution</h4>
                <CityGraph 
                  title="Objective 1 Path" 
                  numCities={activeInstance === 'kroAB100' ? 100 : activeInstance === 'kroAB150' ? 150 : activeInstance === 'kroAB200' ? 200 : 40}
                  showPath={true}
                  selectedCity={5 + selectedSolution}
                />
              </div>
              <div className="h-full">
                <h4 className="text-sm font-medium mb-2">Objective 2 Solution</h4>
                <CityGraph 
                  title="Objective 2 Path" 
                  numCities={activeInstance === 'kroAB100' ? 100 : activeInstance === 'kroAB150' ? 150 : activeInstance === 'kroAB200' ? 200 : 40}
                  showPath={true}
                  selectedCity={5 + selectedSolution}
                />
              </div>
            </div>
          ) : (
            <div className="flex items-center justify-center h-[400px] text-gray-500 dark:text-gray-400">
              <p>Select a solution from the Pareto front to visualize</p>
            </div>
          )}
        </Card>
      </div>
    </div>
  );
};

export default Visualization;